name: septa-data
channels:
  - conda-forge
dependencies:
  - python=3.8*
  - pyproj
  - geopandas
  - psycopg2
  - geoalchemy2
  - ipython
  - tqdm
  - jupyterlab
  - jupytext
  - pandas-profiling
  - flake8
  - pip
